IMAGE:
  VERSION: "171219910203199431032017/mongo-snackbar:latest"
  #VERSION: "mongo:8.0.1"
  PULL_POLICY: IfNotPresent

STATEFULSET:
  CONTAINER:
    NAME: mongodb-c
  LABEL: mongodb
  REPLICAS: 2
  PORT: 27017
  TOLERATIONS:
    ENABLED: false
    KEY: application
    OPERATOR: Equal
    VALUE: mongodb
    EFFECT: NoSchedule
  NODESELECTOR:
    ENABLED: false
    KEY: application
    VALUE: mongodb

SERVICE:
  NAME: mongodb-clusterip
  TYPE: ClusterIP
  PORT: 27017
  LOAD_BALANCER:
    ENABLED: false
    DNS_SUFFIX: db.snackbar.com.br

PERSISTENCE:
  SIZE: 10Gi
  PATH: /data/db
  PVC_NAME: mongo-pvc

SECRET:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: rootpassword
  MONGODB_USER: snackbaruser
  MONGODB_PASSWORD: snack01
  MONGO_INITDB_DATABASE: snackbar
  DB_HOST: mongodb-clusterip.ns-snackbar.svc.cluster.local
  KEYFILE: JwFrP+6BH0FuiJoaYucVfmMfLpcQZIM0eC9bMoXP